name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: "./"
          output_dir: "./"
          build_html: false
      - name: Show files changed
        run: pwd; ls -la pdfs; tree
      - name: Upload Artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: test
          path: test.pdf
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: test.pdf
          tag: cv
          overwrite: true
