name: Release PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: "./"
          output_dir: "./"
          build_html: false
      - name: Show files changed
        run: pwd; tree
      - name: Upload Artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: test
          path: test.pdf
      - uses: elMuso/MergePDFs-action@1.1
        with:
          path: "./"
          filename: "book.pdf"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "book.pdf"
          tag: cv
          overwrite: true
