name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: text
          output_dir: pdfs
          images_dir: docs/images
          image_import: ./images
          build_html: false
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: pdfs
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "pdfs/test.pdf"
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: pdfs/test.pdf
          asset_name: test.pdf
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
